apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrieval-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retrieval-service
  template:
    metadata:
      labels:
        app: retrieval-service
    spec:
      containers:
        - name: retrieval-service
          image: 015507567103.dkr.ecr.ap-south-1.amazonaws.com/stock-insight/retrieval-service:latest
          ports:
            - containerPort: 8010
          envFrom:
            - secretRef:
                name: db-credentials
          readinessProbe:
            httpGet:
              path: /health
              port: 8010
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8010
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: retrieval-service
spec:
  selector:
    app: retrieval-service
  ports:
    - port: 8010
      targetPort: 8010
  type: ClusterIP

